### ISSUE TITLE
Module Shows in Other Systems

### ISSUE THREAD

**Issue by Vhostym-the-Sojourner** [jopeek/fvtt-dndbeyond-npc-sheet#10]
Description
The module shows for other systems outside of 5e. Can the manifest be updated to be restricted to the compatible system?

Thank you!

Steps to Reproduce

    Go to Module Management in a non-5e system
    The module displays

Versions

    Module: [1.4.3]
    Foundry: [10.291]

**Comment by jopeek** [comment]
Good call. I will try to do that later this week.

**Comment by jopeek** [comment]
Addressed in 1.4.4.

**Comment by Vhostym-the-Sojourner** [comment]
Thank you!
