### ISSUE TITLE
Forge support

### ISSUE THREAD

**Issue by Berlinia** [jopeek/fvtt-dndbeyond-npc-sheet#13]
The module does not seem to work properly with the Forge. I am unable to click on abilities and have them be shown in chat, or expand their description to read what the abilities do. (This was tested obv by disabling all other modules, except the Forge module which is un-disablable).

**Comment by jopeek** [comment]
What dnd5e version?

**Comment by Berlinia** [comment]
3.0 system.

Hey, this was fixed by insalling with manifest link and not updating from Bazaar. The issue is that in your latest update, you didn't change the version number, so it was pulling a previous version of the module.

**Comment by jopeek** [comment]
Hmm I did change the version… I have no experience with Forge or Bazaar so not sure what’s going on there but glad you got it sorted.
