### ISSUE TITLE
dnd npc sheet styling infecting other character sheets with Character Action List

### ISSUE THREAD

**Issue by Brimcon** [jopeek/fvtt-dndbeyond-npc-sheet#2]
With NPC sheet and Action list Module enabled the action list looks like this with the dnd5e Sheet.
![image](https://user-images.githubusercontent.com/7198283/121815429-5bc18000-cc2b-11eb-89c1-2ac0be2f863c.png)

**Comment by jopeek** [comment]
Resolved in 1.3.1 as best as I can. I wrapped all my css classes now so they shouldn't interfere.
