### ISSUE TITLE
Saving throws not showing up

### ISSUE THREAD

**Issue by heyzoms** [jopeek/fvtt-dndbeyond-npc-sheet#9]
For some reason saving throws are not showing up.

The only problem i see i might be doing is switching from tidy sheets to this one doesn't bring saving throws over?

**Comment by jopeek** [comment]
Yeah must be some interference because it works fine for me.

**Comment by SaintLoda** [comment]
> For some reason saving throws are not showing up.
> 
> The only problem i see i might be doing is switching from tidy sheets to this one doesn't bring saving throws over?

I am also having this issue - were you able to find a solution? I've tried disabling all other modules and activating just this module, but it still doesn't work. Here is a screen shot of what it looks like.
![image](https://user-images.githubusercontent.com/124535132/217344874-51f30537-98bd-40b8-887a-deabb01511e9.png)

**Comment by jopeek** [comment]
There are no other saving throws there. Just click STR for example and then choose check or save.

**Comment by SaintLoda** [comment]
Thanks for responding. First, thanks for this awesome module. It's so much easier to reference all features and abilities on one page than the standard character sheet.
A recommendation - would it be possible to see Saving Throws as a separate line? Same as it's seen on DnDBeyond, like this:
![image](https://user-images.githubusercontent.com/124535132/217353115-2816cf61-c756-40dc-baa4-4ba3358793bc.png)

**Comment by jopeek** [comment]
Oh you know what, thanks for that screenshot. Maybe they did disappear… I’ll look into it. I agree it would be better.

**Comment by jopeek** [comment]
Addressed in 1.4.4.
